setup:
  queue: 'milano'
  account: ''
  root_dir: ''
  exp: ''
  run: 5
  det_type: 'Rayonix'
  cell: ''

elog_display:

fetch_mask:
  dataset: '/data/data'

fetch_geom:

build_mask:
  thresholds: -10 5000
  n_images: 20
  n_edge: 1
  combine: True

run_analysis:
  max_events: -1
  ncores: 2

opt_geom:
  dx: -6 6 5
  dy: -6 6 5
  n_iterations: 5
  n_peaks: 4
  threshold: 1000000

find_peaks:
  tag: ''
  psana_mask: False
  min_peaks: 10
  max_peaks: 2048
  npix_min: 2
  npix_max: 30
  amax_thr: 40.
  atot_thr: 180.
  son_min: 10.0
  peak_rank: 3
  r0: 3.0
  dr: 2.0
  nsigm: 10.0

index:
  time: '1:30:00'
  ncores: 64
  tag: ''
  tag_cxi: ''
  int_radius: '3,4,5'
  methods: 'mosflm'
  tolerance: '5,5,5,1.5'
  no_revalidate: True
  multi: True
  profile: True
  cell: ''

stream_analysis:
  tag: ''
  cell_only: False
  ncores: 6

merge:
  tag: ''
  symmetry: '4/mmm_uac'
  iterations: 1
  model: 'unity'
  foms: 'CCstar Rsplit'
  nshells: 10
  highres: 2.5

solve:
  tag: ''
  pdb: ''
